//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCS_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c:\Temp\DSCsave.
        /// </summary>
        internal static string DefaultSaveDirectory {
            get {
                return ResourceManager.GetString("DefaultSaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyAnalysis.
        /// </summary>
        internal static string DefaultSaveLabel {
            get {
                return ResourceManager.GetString("DefaultSaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c:\Temp\Source.
        /// </summary>
        internal static string DefaultSourceDirectory {
            get {
                return ResourceManager.GetString("DefaultSourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name the reference dataset.
        /// </summary>
        internal static string DefaultSourceLabel {
            get {
                return ResourceManager.GetString("DefaultSourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c:\Temp\Target.
        /// </summary>
        internal static string DefaultTargetDirectory {
            get {
                return ResourceManager.GetString("DefaultTargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the dataset to be investigated.
        /// </summary>
        internal static string DefaultTargetLabel {
            get {
                return ResourceManager.GetString("DefaultTargetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Dicom Dose Batch Comparison Utility.
        ///        Expects  - Two folders, each filled with dicom dose files from the same patient,
        ///                 - The expected difference is that they were in some way calculated differently
        ///        Each of the following folders can have subfolders, they don&apos;t need to match layout.
        ///        Source - The set of Files you Trust
        ///        Target - The set of Files you want to determine how different they are from source
        ///Save - Directory you want to save the resu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntroParagraph {
            get {
                return ResourceManager.GetString("IntroParagraph", resourceCulture);
            }
        }
    }
}
