//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSClibrary.Tests.Properties; 
using System;


/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSClibraryTests.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P1_2_mm_e_100A_10_0_02_3 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P1_2_mm_e_100A_10_0_02_3", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P1_2_mm_F_100A_10_0_0_2 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P1_2_mm_F_100A_10_0_0_2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P1_2_mm_X_100A_10_0_0_2 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P1_2_mm_X_100A_10_0_0_2", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P1_5_mm_e_100A_10_0_5_13 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P1_5_mm_e_100A_10_0_5_13", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P1_5_mm_F_100A_10_0_5 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P1_5_mm_F_100A_10_0_5", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P1_5_mm_X_100A_10_0_5 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P1_5_mm_X_100A_10_0_5", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P1_Acuros_F_100X_10_0_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P1_Acuros_F_100X_10_0_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P1_Acuros_X_100X_10_0_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P1_Acuros_X_100X_10_0_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P1Ref_e_100A_10_0_1_13 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P1Ref_e_100A_10_0_1_13", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P1Ref_F_100A_10_0_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P1Ref_F_100A_10_0_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P1Ref_X_100A_10_0_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P1Ref_X_100A_10_0_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P2_10_1_F_100X_10_1_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P2_10_1_F_100X_10_1_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P2_10_1_X_100X_10_1_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P2_10_1_X_100X_10_1_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P3_11_0_F_100X_10_1_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P3_11_0_F_100X_10_1_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P3_11_0_X_100X_10_1_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P3_11_0_X_100X_10_1_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P4_E_2D_e_100A_10_0_1_12 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P4_E_2D_e_100A_10_0_1_12", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P4_E_None_e_100A_10_0_1_N {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P4_E_None_e_100A_10_0_1_N", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P5_Varied_MU_e_095A_10_0_1_13 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_e_095A_10_0_1_13", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P5_Varied_MU_e_099A_10_0_1_13 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_e_099A_10_0_1_13", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P5_Varied_MU_e_101A_10_0_1_13 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_e_101A_10_0_1_13", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P5_Varied_MU_F_095A_10_0_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_F_095A_10_0_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P5_Varied_MU_F_099A_10_0_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_F_099A_10_0_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P5_Varied_MU_F_101A_10_0_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_F_101A_10_0_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P5_Varied_MU_X_095A_10_0_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_X_095A_10_0_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P5_Varied_MU_X_099A_10_0_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_X_099A_10_0_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RD_UnitTest_P5_Varied_MU_X_101A_10_0_1 {
        get {
            object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_X_101A_10_0_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RP_UnitTest_P1_2_mm {
        get {
            object obj = ResourceManager.GetObject("RP_UnitTest_P1_2_mm", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RP_UnitTest_P1_5_mm {
        get {
            object obj = ResourceManager.GetObject("RP_UnitTest_P1_5_mm", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RP_UnitTest_P1_Acuros {
        get {
            object obj = ResourceManager.GetObject("RP_UnitTest_P1_Acuros", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RP_UnitTest_P1Ref {
        get {
            object obj = ResourceManager.GetObject("RP_UnitTest_P1Ref", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RP_UnitTest_P2_10_1 {
        get {
            object obj = ResourceManager.GetObject("RP_UnitTest_P2_10_1", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RP_UnitTest_P3_11_0 {
        get {
            object obj = ResourceManager.GetObject("RP_UnitTest_P3_11_0", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RP_UnitTest_P4_E_2D {
        get {
            object obj = ResourceManager.GetObject("RP_UnitTest_P4_E_2D", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RP_UnitTest_P4_E_None {
        get {
            object obj = ResourceManager.GetObject("RP_UnitTest_P4_E_None", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] RP_UnitTest_P5_Varied_MU {
        get {
            object obj = ResourceManager.GetObject("RP_UnitTest_P5_Varied_MU", resourceCulture);
            return ((byte[])(obj));
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Source,Target,Pass,Fail,Total,Dta/Gamma,Threshhold,Difference,Distance,Abs/Rel
    ///RD.UnitTest.P1Ref.X-100A-10.0-1,RD.UnitTest.P5 Varied MU.X-101A-10.0-1,24277,15523,39800,DTA ,0,0.1,0,Abs
    ///RD.UnitTest.P1Ref.X-100A-10.0-1,RD.UnitTest.P5 Varied MU.X-101A-10.0-1,39800,0,39800,DTA ,0,1,0,Abs
    ///RD.UnitTest.P1Ref.X-100A-10.0-1,RD.UnitTest.P5 Varied MU.X-101A-10.0-1,29,15523,15552,DTA ,10,0.1,0,Abs
    ///RD.UnitTest.P1Ref.X-100A-10.0-1,RD.UnitTest.P5 Varied MU.X-101A-10.0-1,31152,8648,39800,DTA ,0,0.1,1,Abs
    ///RD.UnitTest.P [rest of string was truncated]&quot;;.
    /// </summary>
    public static string SNC_Patient_Comparisons {
        get {
            return ResourceManager.GetString("SNC_Patient_Comparisons", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    public static string TextFile1 {
        get {
            return ResourceManager.GetString("TextFile1", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized resource of type System.Byte[].
    /// </summary>
    public static byte[] X06_OPEN_30X30_PDDCRIN_TBA_180406_16_02_52 {
        get {
            object obj = ResourceManager.GetObject("X06_OPEN_30X30_PDDCRIN_TBA_180406_16_02_52", resourceCulture);
            return ((byte[])(obj));
        }
    }
}
