//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSCTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSCTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P1_2_mm_e_100A_10_0_02_3 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P1_2_mm_e_100A_10_0_02_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P1_2_mm_F_100A_10_0_0_2 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P1_2_mm_F_100A_10_0_0_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P1_2_mm_X_100A_10_0_0_2 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P1_2_mm_X_100A_10_0_0_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P1_5_mm_e_100A_10_0_5_13 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P1_5_mm_e_100A_10_0_5_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P1_5_mm_F_100A_10_0_5 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P1_5_mm_F_100A_10_0_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P1_5_mm_X_100A_10_0_5 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P1_5_mm_X_100A_10_0_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P1_Acuros_F_100X_10_0_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P1_Acuros_F_100X_10_0_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P1_Acuros_X_100X_10_0_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P1_Acuros_X_100X_10_0_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P1Ref_e_100A_10_0_1_13 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P1Ref_e_100A_10_0_1_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P1Ref_F_100A_10_0_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P1Ref_F_100A_10_0_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P1Ref_X_100A_10_0_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P1Ref_X_100A_10_0_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P2_10_1_F_100X_10_1_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P2_10_1_F_100X_10_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P2_10_1_X_100X_10_1_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P2_10_1_X_100X_10_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P3_11_0_F_100X_10_1_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P3_11_0_F_100X_10_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P3_11_0_X_100X_10_1_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P3_11_0_X_100X_10_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P4_E_2D_e_100A_10_0_1_12 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P4_E_2D_e_100A_10_0_1_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P4_E_None_e_100A_10_0_1_N {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P4_E_None_e_100A_10_0_1_N", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P5_Varied_MU_e_095A_10_0_1_13 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_e_095A_10_0_1_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P5_Varied_MU_e_099A_10_0_1_13 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_e_099A_10_0_1_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P5_Varied_MU_e_101A_10_0_1_13 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_e_101A_10_0_1_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P5_Varied_MU_F_095A_10_0_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_F_095A_10_0_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P5_Varied_MU_F_099A_10_0_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_F_099A_10_0_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P5_Varied_MU_F_101A_10_0_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_F_101A_10_0_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P5_Varied_MU_X_095A_10_0_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_X_095A_10_0_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P5_Varied_MU_X_099A_10_0_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_X_099A_10_0_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RD_UnitTest_P5_Varied_MU_X_101A_10_0_1 {
            get {
                object obj = ResourceManager.GetObject("RD_UnitTest_P5_Varied_MU_X_101A_10_0_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TextFile1 {
            get {
                return ResourceManager.GetString("TextFile1", resourceCulture);
            }
        }
    }
}
